require 'user.plugins'
require 'user.options'
--lsp_installer must setup before lspconfig
require 'user.lsp_installer'
require 'user.treesitter'
require 'user.lualine'
require 'user.cmp'
require 'user.gitsigns'
--require 'user.comment'
require 'user.telescope'
require 'user.tree'
require 'user.keymaps'
require 'user.luasnip'
--require 'user.dap'
require 'user.outline'
require 'user.autopairs'
